<?php

/**
 * PluginWorker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginWorker extends BaseWorker
{
  const STATUS_PROCESSING = 1;
  const STATUS_PROCESSED  = 2;
  const STATUS_PENDING    = 3;

  protected
    $return_value = null,
    $output       = null;

  public function run()
  {
    exec($this->getFullCommand(), $this->output, $this->return_value);

    return $this->return_value;
  }

  public function getOutput()
  {
    if ($this->return_value === null)
    {
      throw new RuntimeException('This worker has not been run yet');
    }

    return implode(PHP_EOL, $this->output);
  }

  protected function getFullCommand()
  {
    return sprintf('%s %s', $this->getCommand(), $this->getArgv());
  }

  public function preInsert($event)
  {
    if (!$this->_get('status'))
    {
      $this->_set('status', Worker::STATUS_PENDING);
    }
  }

  public function setProcessing()
  {
    $this->setStartedAt(date('Y-m-d H:i:s'));
    $this->setStatus(Worker::STATUS_PROCESSING);
    $this->save();
  }

  public function setProcessed()
  {
    $this->setProcessedAt(date('Y-m-d H:i:s'));
    $this->setStatus(Worker::STATUS_PROCESSED);
    $this->save();
  }

  public function setPending()
  {
    $this->setStatus(Worker::STATUS_PENDING);
    $this->save();
  }
}
